# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://namsuji.github.io/test
title: For Web Programmer
email: 01928abcd@naver.com
author: Nam
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   2nd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/NamSuJi
  - title: Naver
    url: https://blog.naver.com/01928abcd
