# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://apps.alecrem.com/koyomito
title: Koyomito
email: ale@alecrem.com
author: Alejandro Cremades
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2017 Alejandro Cremades. Todos los derechos reservados.'
credits: 'Envía correo electrónico a Alejandro desde su sitio web <a href="https://alecrem.com/">Alecrem</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/alecrem
  - title: instagram
    url: https://www.instagram.com/karawapo/
  - title: youtube
    url: https://www.youtube.com/karawapo
  - title: facebook
    url: https://www.facebook.com/alecrem
